dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  # command to install dependencies
install:
  - pip install -r requirements.test.txt -U
  - pip install -r requirements.txt -U
# command to run tests
script:
  - python -m pytest tests
